/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parker.serb.REP;

import java.awt.Color;
import java.sql.Timestamp;
import java.util.Date;
import java.util.List;
import parker.serb.Global;
import parker.serb.sql.REPBoardActionType;
import parker.serb.sql.REPCase;
import parker.serb.sql.User;
import parker.serb.util.NumberFormatService;

/**
 *
 * @author parkerjohnston
 */
public class REPBoardStatusPanel extends javax.swing.JPanel {

    REPCase caseInformation;
    /**
     * Creates new form REPBoardStatusPanel
     */
    public REPBoardStatusPanel() {
        initComponents();
        addBoardMeetingButton.setVisible(false);
    }
    
    public void loadHearingPerson() {
        hearingPersonComboBox.removeAllItems();
        
        hearingPersonComboBox.addItem("");
        
        List hearingPeopleList = User.loadULPComboBox();
        
        for (Object hearingPerson : hearingPeopleList) {
            hearingPersonComboBox.addItem(hearingPerson.toString());
        }
    }
    
    public void loadBoardActionType() {
        boardActionTypeComboBox.removeAllItems();
        
        boardActionTypeComboBox.addItem("");
        
        List boardActionTypeList = REPBoardActionType.loadAllREPBoardActionTypes();
        
        for (Object boardAction : boardActionTypeList) {
            boardActionTypeComboBox.addItem(boardAction.toString());
        }
    }
    
    public void loadInformation() {
        loadHearingPerson();
        loadBoardActionType();
        //loadMeetings
        loadStatusInformation();
    }
    
    private void loadStatusInformation() {
        caseInformation = REPCase.loadBoardStatus();
        
        boardActionTypeComboBox.setSelectedItem(caseInformation.boardActionType);
        boardActionDateTextBox.setText(caseInformation.boardActionDate != null ? Global.mmddyyyy.format(new Date(caseInformation.boardActionDate.getTime())) : ""); 
        hearingPersonComboBox.setSelectedItem(caseInformation.hearingPersonID == 0 ? "" : User.getNameByID(caseInformation.hearingPersonID));
        BoardActionNote.setText(caseInformation.boardStatusNote);
    }
    
    void enableUpdate() {
        Global.root.getjButton2().setText("Save");
        
        Global.root.getjButton9().setVisible(true);
        
        boardActionTypeComboBox.setEnabled(true);
        boardActionDateTextBox.setEnabled(true);
        boardActionDateTextBox.setBackground(Color.WHITE);
        hearingPersonComboBox.setEnabled(true);
        BoardActionNote.setEnabled(true);
        BoardMeetingBlurb.setEnabled(true);
        
        addBoardMeetingButton.setVisible(true);
    }
    
    void disableUpdate(boolean runSave) {
        Global.root.getjButton2().setText("Update");
        
        Global.root.getjButton9().setVisible(false);
        
        boardActionTypeComboBox.setEnabled(false);
        boardActionDateTextBox.setEnabled(false);
        boardActionDateTextBox.setBackground(new Color(238,238,238));
        hearingPersonComboBox.setEnabled(false);
        BoardActionNote.setEnabled(false);
        BoardMeetingBlurb.setEnabled(false);
        
        addBoardMeetingButton.setVisible(false);
        
        if(runSave) {
            saveInformation();
        } else {
            loadStatusInformation();
        }
            
    }
    
    private void saveInformation() {
        REPCase newCaseInformation = new REPCase();
        
        newCaseInformation.boardActionType = boardActionTypeComboBox.getSelectedItem().toString().equals("") ? null : boardActionTypeComboBox.getSelectedItem().toString();
        newCaseInformation.boardActionDate = boardActionDateTextBox.getText().equals("") ? null : new Timestamp(NumberFormatService.convertMMDDYYYY(boardActionDateTextBox.getText()));
        newCaseInformation.hearingPersonID = hearingPersonComboBox.getSelectedItem().toString().equals("") ? null : User.getUserID(hearingPersonComboBox.getSelectedItem().toString());
        newCaseInformation.boardStatusNote = BoardActionNote.getText().equals("") ? null : BoardActionNote.getText();
        newCaseInformation.boardStatusBlurb = BoardMeetingBlurb.getText().equals("") ? null : BoardMeetingBlurb.getText();
        
        REPCase.updateBoardStatus(newCaseInformation, caseInformation);
        caseInformation = REPCase.loadBoardStatus();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boardActionTypeComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        boardActionDateTextBox = new com.alee.extended.date.WebDateField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BoardActionNote = new javax.swing.JTextArea();
        hearingPersonComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BoardMeetingBlurb = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addBoardMeetingButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Type:");

        boardActionTypeComboBox.setEnabled(false);

        jLabel2.setText("Board Action Date:");

        boardActionDateTextBox.setBackground(new java.awt.Color(238, 238, 238));
        boardActionDateTextBox.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        boardActionDateTextBox.setEnabled(false);
        boardActionDateTextBox.setDateFormat(Global.mmddyyyy);

        jLabel3.setText("Hearing Person:");

        jLabel4.setText("Note:");

        BoardActionNote.setColumns(20);
        BoardActionNote.setLineWrap(true);
        BoardActionNote.setRows(5);
        BoardActionNote.setWrapStyleWord(true);
        BoardActionNote.setEnabled(false);
        jScrollPane1.setViewportView(BoardActionNote);

        hearingPersonComboBox.setEnabled(false);

        jLabel6.setText("Board Action:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boardActionTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boardActionDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hearingPersonComboBox, 0, 108, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boardActionTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(boardActionDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(hearingPersonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
        );

        jLabel5.setText("Blurb:");

        BoardMeetingBlurb.setColumns(20);
        BoardMeetingBlurb.setLineWrap(true);
        BoardMeetingBlurb.setRows(5);
        BoardMeetingBlurb.setWrapStyleWord(true);
        BoardMeetingBlurb.setEnabled(false);
        jScrollPane3.setViewportView(BoardMeetingBlurb);

        jPanel3.setMaximumSize(new java.awt.Dimension(300, 155));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 155));

        jLabel7.setText("Board Meeting Information:");

        addBoardMeetingButton.setText("+");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meeting Date", "Agenda Item", "Status/Recommendation", "Memo Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 155));
        jTable1.setMinimumSize(new java.awt.Dimension(300, 155));
        jTable1.setPreferredSize(new java.awt.Dimension(300, 155));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBoardMeetingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBoardMeetingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BoardActionNote;
    private javax.swing.JTextArea BoardMeetingBlurb;
    private javax.swing.JButton addBoardMeetingButton;
    private com.alee.extended.date.WebDateField boardActionDateTextBox;
    private javax.swing.JComboBox boardActionTypeComboBox;
    private javax.swing.JComboBox hearingPersonComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
