/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parker.serb.report;

//TODO: Load all REP Reports

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import parker.serb.Global;
import parker.serb.sql.CMDSReport;
import parker.serb.sql.SMDSDocuments;
import parker.serb.util.Item;

/**
 *
 * @author parker
 */
public class ReportDialog extends javax.swing.JDialog {

    String section;
    
    /**
     * Creates new form REPReportDialog
     * @param parent
     * @param modal
     * @param sectionPassed
     */
    public ReportDialog(java.awt.Frame parent, boolean modal, String sectionPassed) {
        super(parent, modal);
        initComponents();
        section = sectionPassed;
        loadReports();
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    }
    
    private void loadReports() {
        DefaultComboBoxModel dt = new DefaultComboBoxModel();
        ReportComboBox.setModel(dt);
        ReportComboBox.addItem(new Item<>("0", ""));
        
        switch (Global.activeSection) {
            case "REP":
            case "ULP":
            case "MED":
            case "ORG":
            case "Hearings":
                List<SMDSDocuments> smdsletterList = SMDSDocuments.loadDocumentNamesByTypeAndSection(section, "Report");
                
                for (SMDSDocuments letter : smdsletterList) {
                    ReportComboBox.addItem(new Item<>(String.valueOf(letter.id), letter.description));
                }
                ReportComboBox.setSelectedItem(new Item<>("0", ""));
                break;
            case "Civil Service Commission":
            case "CMDS":
                List<CMDSReport> cmdsletterList = CMDSReport.loadActiveReportsBySection(section);

                for (CMDSReport letter : cmdsletterList) {
                    ReportComboBox.addItem(new Item<>(String.valueOf(letter.id), letter.description));
                }
                ReportComboBox.setSelectedItem(new Item<>("0", ""));

                break;
            default:
                break;
        }

    }

    private void generateReport() {
        Item item = (Item) ReportComboBox.getSelectedItem();
        int id = Integer.parseInt(item.getValue().toString());
        
        switch (Global.activeSection) {
            case "REP":
            case "ULP":
            case "MED":
            case "ORG":
            case "Hearings":
                SMDSDocuments report = SMDSDocuments.findDocumentByID(id);
                GenerateReport.runReport(report);
                break;
            case "Civil Service Commission":
            case "CMDS":
                CMDSReport cmdsreport = CMDSReport.getReportByID(id);
        
                SMDSDocuments SMDSreport = new SMDSDocuments();
                SMDSreport.section = cmdsreport.section;
                SMDSreport.description = cmdsreport.description;
                SMDSreport.fileName = cmdsreport.fileName;
                SMDSreport.parameters = cmdsreport.parameters;

                GenerateReport.runReport(SMDSreport);
                break;
            default:
                break;
        }
        
        
    }

    private void enableGenerateButton() {
        if(ReportComboBox.getSelectedItem().toString().equals("")) {
            GenerateButton.setEnabled(false);
        } else {
            GenerateButton.setEnabled(true);
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ReportComboBox = new javax.swing.JComboBox();
        GenerateButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generate Report");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please Select a Report to Generate");

        ReportComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportComboBoxActionPerformed(evt);
            }
        });

        GenerateButton.setText("Generate");
        GenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReportComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                        .addComponent(GenerateButton))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateButtonActionPerformed
        generateReport();
    }//GEN-LAST:event_GenerateButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ReportComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportComboBoxActionPerformed
        enableGenerateButton();
    }//GEN-LAST:event_ReportComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton GenerateButton;
    private javax.swing.JComboBox ReportComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
