/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parker.serb.report;

import com.alee.extended.date.WebCalendar;
import com.alee.utils.swing.Customizer;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import parker.serb.Global;
import parker.serb.sql.SMDSDocuments;
import parker.serb.sql.User;
import parker.serb.util.Item;
import parker.serb.util.StringUtilities;

/**
 *
 * @author User
 */
public class RequestedInfoTwoDateIDPanel extends javax.swing.JDialog {

    SMDSDocuments report;

    /**
     * Creates new form RequestedReportInformationPanel
     *
     * @param parent
     * @param modal
     * @param reportPassed
     * @param IDType
     */
    public RequestedInfoTwoDateIDPanel(java.awt.Frame parent, boolean modal, SMDSDocuments reportPassed, String IDType) {
        super(parent, modal);
        report = reportPassed;
        initComponents();
        setActive(report.fileName, IDType);
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    }

    private void setActive(String reportName, String IDType) {
        reportLabel.setText(reportName);
        switch (IDType) {
            case "UserID":
                comboBoxLabel.setText("User:");
                break;
            case "InvestigatorID":
                comboBoxLabel.setText("Investigator:");
                break;
            case "SectionUserID":
                comboBoxLabel.setText("User:");
                break;
            default:
                break;
        }
        loadCombobox(IDType);
        generateButton();
    }

    private void loadCombobox(String IDType) {
        List<User> userList = null;

        DefaultComboBoxModel dt = new DefaultComboBoxModel();
        ComboBox.setModel(dt);
        ComboBox.addItem(new Item<>("0", ""));

        switch (IDType) {
            case "UserID":
                ComboBox.addItem(new Item<>("%", "All"));
                userList = User.getEnabledUsers();
                for (User item : userList) {
                    ComboBox.addItem(new Item<>(
                            String.valueOf(item.id),
                            StringUtilities.buildFullName(item.firstName, item.middleInitial, item.lastName))
                    );
                }
            case "InvestigatorID":
                ComboBox.addItem(new Item<>("%", "All"));
                userList = User.getEnabledUsers();

                for (User item : userList) {
                    if (IDType.equals("InvestigatorID") && item.investigator) {
                        ComboBox.addItem(new Item<>(
                                String.valueOf(item.id),
                                StringUtilities.buildFullName(item.firstName, item.middleInitial, item.lastName))
                        );
                    }
                }
                break;
                case "SectionUserID":
                ComboBox.addItem(new Item<>("%", "All"));
                List<User> sectionUserList = User.loadSectionUsersWithID(Global.activeSection);
                for (User item : sectionUserList) {
                    ComboBox.addItem(new Item<>(
                            String.valueOf(item.id),
                            StringUtilities.buildFullName(item.firstName, item.middleInitial, item.lastName))
                    );
                }
                ComboBox.setSelectedItem(new Item<>("%", "All"));
                break;
            default:
                break;
        }
        ComboBox.setSelectedItem(new Item<>("0", ""));
    }

    private void generateButton() {
        if (startDateField.toString().trim().equals("")
                || endDateField.toString().trim().equals("")
                || ComboBox.getSelectedItem().toString().equals("")) {
            GenerateReportButton.setEnabled(false);
        } else {
            GenerateReportButton.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startDateField = new com.alee.extended.date.WebDateField();
        jLabel7 = new javax.swing.JLabel();
        endDateField = new com.alee.extended.date.WebDateField();
        comboBoxLabel = new javax.swing.JLabel();
        GenerateReportButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        reportLabel = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Required Report Information");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Required Report Information");

        startDateField.setEditable(false);
        startDateField.setDateFormat(Global.mmddyyyy);

        startDateField.setCalendarCustomizer(new Customizer<WebCalendar> ()
            {
                @Override
                public void customize ( final WebCalendar calendar )
                {
                    calendar.setStartWeekFromSunday ( true );
                }
            } );
            startDateField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    startDateFieldActionPerformed(evt);
                }
            });

            jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
            jLabel7.setText("Start Date:");

            endDateField.setEditable(false);
            endDateField.setDateFormat(Global.mmddyyyy);

            endDateField.setCalendarCustomizer(new Customizer<WebCalendar> ()
                {
                    @Override
                    public void customize ( final WebCalendar calendar )
                    {
                        calendar.setStartWeekFromSunday ( true );
                    }
                } );
                endDateField.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        endDateFieldActionPerformed(evt);
                    }
                });

                comboBoxLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                comboBoxLabel.setText("<<LABEL>>");

                GenerateReportButton.setText("Generate Report");
                GenerateReportButton.setEnabled(false);
                GenerateReportButton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        GenerateReportButtonActionPerformed(evt);
                    }
                });

                CancelButton.setText("Cancel");
                CancelButton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CancelButtonActionPerformed(evt);
                    }
                });

                reportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                reportLabel.setText("<<REPORTNAME>>");

                ComboBox.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ComboBoxActionPerformed(evt);
                    }
                });

                jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel9.setText("End Date:");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                            .addComponent(reportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GenerateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(endDateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(reportLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelButton)
                            .addComponent(GenerateReportButton))
                        .addContainerGap())
                );

                layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ComboBox, comboBoxLabel, endDateField, jLabel7, jLabel9, startDateField});

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void GenerateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportButtonActionPerformed
        Item item = (Item) ComboBox.getSelectedItem();
        GenerateReport.generateTwoDatesIDReport(startDateField.getText(), endDateField.getText(), item.getValue().toString(), report);
    }//GEN-LAST:event_GenerateReportButtonActionPerformed

    private void startDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateFieldActionPerformed
        generateButton();
    }//GEN-LAST:event_startDateFieldActionPerformed

    private void endDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateFieldActionPerformed
        generateButton();
    }//GEN-LAST:event_endDateFieldActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        generateButton();
    }//GEN-LAST:event_ComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox ComboBox;
    private javax.swing.JButton GenerateReportButton;
    private javax.swing.JLabel comboBoxLabel;
    private com.alee.extended.date.WebDateField endDateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel reportLabel;
    private com.alee.extended.date.WebDateField startDateField;
    // End of variables declaration//GEN-END:variables
}
