/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parker.serb.report;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import parker.serb.Global;
import parker.serb.sql.ActivityType;
import parker.serb.sql.SMDSDocuments;
import parker.serb.sql.User;
import parker.serb.util.Item;
import parker.serb.util.StringUtilities;

/**
 *
 * @author User
 */
public class RequestedInfoComboBoxStringPanel extends javax.swing.JDialog {

    SMDSDocuments report;

    /**
     * Creates new form RequestedReportInformationPanel
     *
     * @param parent
     * @param modal
     * @param reportPassed
     * @param IDType
     */
    public RequestedInfoComboBoxStringPanel(java.awt.Frame parent, boolean modal, SMDSDocuments reportPassed, String IDType) {
        super(parent, modal);
        report = reportPassed;
        initComponents();
        setActive(report.fileName, IDType);
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    }

    private void setActive(String reportName, String IDType) {
        reportLabel.setText(reportName);
        switch (IDType) {
            case "ActivityType, Year":
                comboBoxLabel.setText("Activity Type: ");
                TextFieldLabel.setText("Year: ");
                break;
            case "InvestigatorID, Year":
                comboBoxLabel.setText("Investigator: ");
                TextFieldLabel.setText("Year: ");
                break;
            default:
                break;
        }
        loadCombobox(IDType);
        generateButton();
    }

    private void loadCombobox(String IDType) {
        List<User> userList = null;

        DefaultComboBoxModel dt = new DefaultComboBoxModel();
        ComboBox.setModel(dt);
        ComboBox.addItem(new Item<>("%", "All"));

        switch (IDType) {
            case "ActivityType, Year":
                List<ActivityType> typeList = ActivityType.loadAllActivityTypeBySection(Global.activeSection);
                for (ActivityType item : typeList) {
                    ComboBox.addItem(new Item<>(
                            String.valueOf(item.id),
                            item.descriptionFull)
                    );
                }
            case "InvestigatorID, Year":
                userList = User.getEnabledInvestigators();
                for (User item : userList) {
                    if (item.investigator) {
                        ComboBox.addItem(new Item<>(
                                String.valueOf(item.id),
                                StringUtilities.buildFullName(item.firstName, item.middleInitial, item.lastName))
                        );
                    }
                }
                break;
            default:
                break;
        }
        ComboBox.setSelectedItem(new Item<>("%", "All"));
    }

    private void generateButton() {
        if (TextField.getText().trim().equals("") || ComboBox.getSelectedIndex() < 0) {
            GenerateReportButton.setEnabled(false);
        } else {
            GenerateReportButton.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxLabel = new javax.swing.JLabel();
        GenerateReportButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        reportLabel = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox();
        TextFieldLabel = new javax.swing.JLabel();
        TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Required Report Information");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Required Report Information");

        comboBoxLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        comboBoxLabel.setText("<<LABEL>>");

        GenerateReportButton.setText("Generate Report");
        GenerateReportButton.setEnabled(false);
        GenerateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        reportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportLabel.setText("<<REPORTNAME>>");

        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        TextFieldLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TextFieldLabel.setText("<<LABEL>>");

        TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(reportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GenerateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(reportLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(GenerateReportButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ComboBox, comboBoxLabel});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void GenerateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportButtonActionPerformed
        Item item = (Item) ComboBox.getSelectedItem();
        String comboBoxID = item.getValue().toString();
        if (item.getDescription().equals("All")){
            comboBoxID = "%";
        }
        GenerateReport.generateIDStringReport(comboBoxID, TextField.getText().trim(), report);
    }//GEN-LAST:event_GenerateReportButtonActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        generateButton();
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldKeyTyped
        generateButton();
    }//GEN-LAST:event_TextFieldKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox ComboBox;
    private javax.swing.JButton GenerateReportButton;
    private javax.swing.JTextField TextField;
    private javax.swing.JLabel TextFieldLabel;
    private javax.swing.JLabel comboBoxLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel reportLabel;
    // End of variables declaration//GEN-END:variables
}
