/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parker.serb.companySearch;

import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import parker.serb.Global;
import parker.serb.sql.EmployerCaseSearchData;
import parker.serb.sql.MEDCaseSearchData;

/**
 *
 * @author parkerjohnston
 */
public class companySearchPanel extends javax.swing.JPanel {

    DefaultTableModel model;
    List caseList;
    /**
     * Creates new form companySearchPanel
     */
    public companySearchPanel() {
        initComponents();
        addListeners();
    }
    
    private void addListeners() {
        employerSearchTerm.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
//                Global.employerSearchTerm = employerSearchTerm.getText().trim();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
//                Global.employerSearchTerm = employerSearchTerm.getText().trim();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
//                Global.employerSearchTerm = employerSearchTerm.getText().trim();
            }
        });
        
    }
    
    public void loadPastData() {
        if(Global.employerSearchTerm != null) {
            employerSearchTerm.setText(Global.employerSearchTerm);
        }
    }
    
    public void loadAllCases() {
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }   
        };
//       
//        model.addColumn("Case Number");
//        model.addColumn("Employer Name");
//        model.addColumn("Union Name");
//        model.addColumn("County");
//        model.addColumn("Employer ID");
//        model.addColumn("BUN Number");
        
        caseList = EmployerCaseSearchData.loadEmployerCaseList();
        
        for (Object caseItem : caseList) {
            EmployerCaseSearchData act = (EmployerCaseSearchData) caseItem;
            
            model.addRow(new Object[] {
                (act.caseYear + "-" + act.caseType + "-" + act.caseMonth + "-" + act.caseNumber),
                "", //employer name
                "", //union name
                "", //county
                "" //BUN Number
            }); 
        }
//        getTableData();
        employerTable.setModel(model);
//        jLayeredPane1.moveToBack(jPanel1);
        
    }

    public DefaultTableModel getModel() {
        return model;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employerTable = new javax.swing.JTable();
        employerSearchTerm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Search:");

        employerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Case Number", "Status", "File Date", "Employer", "Parties"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employerTable);

        employerSearchTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employerSearchTermActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Status:");

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Open", "Closed" }));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employerSearchTerm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(employerSearchTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        statusComboBox.setSelectedItem("All");
        employerSearchTerm.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void employerSearchTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employerSearchTermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employerSearchTermActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void employerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employerTableMouseClicked
        if(evt.getClickCount() == 2) {
            String caseNumber = employerTable.getValueAt(employerTable.getSelectedRow(), 0).toString();
            
            switch(caseNumber.split("-")[1]) {
                case "MED":
                    Global.root.getjTabbedPane1().setSelectedIndex(Global.root.getjTabbedPane1().indexOfTab("MED"));
                    Global.root.getmEDHeaderPanel1().getjComboBox2().setSelectedItem(caseNumber);
//                    Global.root.getjTabbedPane1().setSelectedIndex(WIDTH);
            }
        }
        
    }//GEN-LAST:event_employerTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField employerSearchTerm;
    private javax.swing.JTable employerTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> statusComboBox;
    // End of variables declaration//GEN-END:variables
}
