/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parker.serb.boardmeetings;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import parker.serb.Global;
import parker.serb.sql.BoardMeeting;
import parker.serb.sql.REPRecommendation;
import parker.serb.sql.ULPRecommendation;

/**
 *
 * @author parkerjohnston
 */
public class AddREPBoardMeeting extends javax.swing.JDialog {

    /**
     * Creates new form AddULPBoardMeeting
     */
    public AddREPBoardMeeting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addListeners();
        loadRecComboBox();
        setLocationRelativeTo(parent);
        setVisible(true);
    }
    
    private void addListeners() {
        meetingDateTextBox.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                enableAddButton();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                enableAddButton();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                enableAddButton();
            }
        });
        
        agendaItemTextBox.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                enableAddButton();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                enableAddButton();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                enableAddButton();
            }
        });
        
//        recommendationComboBox.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                enableAddButton();
//            }
//        });
    }
    
    private void loadRecComboBox() {
        recommendationComboBox.removeAllItems();
        
        recommendationComboBox.addItem("");
        
        List recommendationList = REPRecommendation.loadAllREPRecommendations();
        
        for (Object recommendation : recommendationList) {
            REPRecommendation rec = (REPRecommendation) recommendation;
            recommendationComboBox.addItem(rec.recommendation);
        }
    }
    
    private void enableAddButton() {
        if(meetingDateTextBox.getText().equals("") ||
                agendaItemTextBox.getText().equals("")) {
            addBoardMeetingButton.setEnabled(false);
        } else {
            addBoardMeetingButton.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addBoardMeetingButton = new javax.swing.JButton();
        cancelBoardMeetingButton = new javax.swing.JButton();
        recommendationComboBox = new javax.swing.JComboBox<>();
        agendaItemTextBox = new javax.swing.JTextField();
        meetingDateTextBox = new com.alee.extended.date.WebDateField();
        jLabel5 = new javax.swing.JLabel();
        memoDateTextBox = new com.alee.extended.date.WebDateField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Boarding Meeting");

        jLabel2.setText("Meeting Date:");

        jLabel3.setText("Agenda Item:");

        jLabel4.setText("Recommendation:");

        addBoardMeetingButton.setText("Add");
        addBoardMeetingButton.setEnabled(false);
        addBoardMeetingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBoardMeetingButtonActionPerformed(evt);
            }
        });

        cancelBoardMeetingButton.setText("Cancel");
        cancelBoardMeetingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBoardMeetingButtonActionPerformed(evt);
            }
        });

        recommendationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        recommendationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommendationComboBoxActionPerformed(evt);
            }
        });

        meetingDateTextBox.setEditable(false);
        meetingDateTextBox.setCaretColor(new java.awt.Color(0, 0, 0));
        meetingDateTextBox.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        meetingDateTextBox.setDateFormat(Global.mmddyyyy);

        jLabel5.setText("Memo Date:");

        memoDateTextBox.setEditable(false);
        memoDateTextBox.setCaretColor(new java.awt.Color(0, 0, 0));
        memoDateTextBox.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        memoDateTextBox.setDateFormat(Global.mmddyyyy);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recommendationComboBox, 0, 544, Short.MAX_VALUE)
                            .addComponent(agendaItemTextBox)
                            .addComponent(meetingDateTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(memoDateTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelBoardMeetingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBoardMeetingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(meetingDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(agendaItemTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recommendationComboBox)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(memoDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBoardMeetingButton)
                    .addComponent(cancelBoardMeetingButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBoardMeetingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBoardMeetingButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBoardMeetingButtonActionPerformed

    private void addBoardMeetingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBoardMeetingButtonActionPerformed
        BoardMeeting.addREPBoardMeeting(meetingDateTextBox.getText(), agendaItemTextBox.getText(), recommendationComboBox.getSelectedItem().toString(), memoDateTextBox.getText());
        dispose();
    }//GEN-LAST:event_addBoardMeetingButtonActionPerformed

    private void recommendationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommendationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recommendationComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBoardMeetingButton;
    private javax.swing.JTextField agendaItemTextBox;
    private javax.swing.JButton cancelBoardMeetingButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.alee.extended.date.WebDateField meetingDateTextBox;
    private com.alee.extended.date.WebDateField memoDateTextBox;
    private javax.swing.JComboBox<String> recommendationComboBox;
    // End of variables declaration//GEN-END:variables
}
