/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package parker.serb.MED;

/**
 *
 * @author parker.johnston
 */
public class MEDBulkHandleCases extends javax.swing.JFrame {

    /**
     * Creates new form MEDBulkHandleCases
     * @param parent
     * @param modal
     */
    public MEDBulkHandleCases(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SettleCasesButton = new javax.swing.JButton();
        SendtoBoardButton = new javax.swing.JButton();
        SendtoBoardButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bulk Handle MED Cases");

        SettleCasesButton.setText("Settle Cases");
        SettleCasesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettleCasesButtonActionPerformed(evt);
            }
        });

        SendtoBoardButton.setText("Send to Board");
        SendtoBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendtoBoardButtonActionPerformed(evt);
            }
        });

        SendtoBoardButton1.setText("Close Cases");
        SendtoBoardButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendtoBoardButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .add(closeButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(SettleCasesButton)
                    .add(SendtoBoardButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(SendtoBoardButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {SendtoBoardButton, SendtoBoardButton1, SettleCasesButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(30, 30, 30)
                .add(SettleCasesButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(SendtoBoardButton)
                .add(18, 18, 18)
                .add(SendtoBoardButton1)
                .add(33, 33, 33)
                .add(closeButton)
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {SendtoBoardButton, SendtoBoardButton1, SettleCasesButton}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void SettleCasesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettleCasesButtonActionPerformed
        new MEDBulkSettleCasesDialog(this, true);
    }//GEN-LAST:event_SettleCasesButtonActionPerformed

    private void SendtoBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendtoBoardButtonActionPerformed
        new MEDBulkSendToBoardDialog(this, true);
    }//GEN-LAST:event_SendtoBoardButtonActionPerformed

    private void SendtoBoardButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendtoBoardButton1ActionPerformed
        new MEDBulkClosedCasesDialog(this, true);
    }//GEN-LAST:event_SendtoBoardButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendtoBoardButton;
    private javax.swing.JButton SendtoBoardButton1;
    private javax.swing.JButton SettleCasesButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
